baseURL = "http://ut-notes.casperong.xyz/"
languageCode = "en-us"
title = "Uniform Test Notes"
theme = "ananke"
[taxonomies]
  Science = “Science”
  Geography = "Geography"
  Chis = "Chinese History"
  Math = "Mathemactics"
  His = "History"
  